name: example

on: 
  schedule:
    - cron: "5 */48 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  hello:
    runs-on: windows-latest
    steps:
      - name: show-message
        run: echo "hello framework develop II"
